# Generated by Django 5.0.3 on 2024-04-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='lot_size_acres',
        ),
    ]
